gitGraph
    commit id: "d43f3da Creacion del proyecto"
    commit id: "9489691 Refactor: Limpiar raiz"
    commit id: "bf28b3f feat: Crear clase proceso" tag: "main"
    branch "feat-Interfaz"
    checkout "feat-Interfaz"
    commit id: "f64e42f Feat: Creacion de interfaz"
    commit id: "c12e5a8 Feat: Agregar contenido inicial al README"
    commit id: "e08a4b7 Refactor: Cambios en el orden del directorio del proyecto"
    commit id: "348e708 Feat: Implementar creacion y eliminacion de procesos"
    commit id: "b34934d feat: Creacion de tabla dentro de la interfaz" tag: "HEAD -> feat-Interfaz"
    branch "bug-fix-Problema-interfaz"
    checkout "bug-fix-Problema-interfaz"
    commit id: " bugFix and feat: Corrección de problema en tabla, y agregar actualizacion en tabla" tag: "HEAD -> bug-fix-Problema-interfaz"
    