gitGraph
    commit id: "d43f3da" tag: "Creacion del proyecto"
    commit id: "9489691" tag: "Refactor: Limpiar raiz"
    commit id: "bf28b3f" tag: "feat: Crear clase proceso"
    branch "feat-Interfaz"
    checkout "feat-Interfaz"
    commit id: "f64e42f" tag: "Feat: Creacion de interfaz"
    commit id: "c12e5a8" tag: "Feat: Agregar README"
    commit id: "e08a4b7" tag: "Refactor: Orden directorio"
    commit id: "348e708" tag: "Feat: Crear/eliminar procesos"
    commit id: "b34934d" tag: "feat: Tabla interfaz"
    commit id: "a91531e" tag: "Agregar scroll y grafo"
    commit id: "57a47d2" tag: "Actualizar grafico"
    branch "bug-fix-Problema-interfaz"
    checkout "bug-fix-Problema-interfaz"
    commit id: "f23a04a" tag: "Cambios en interfaz"
    commit id: "d7a76fb" tag: "Merge cambios remote"
    commit id: "87c64f9" tag: "Modificar tiempo"
    checkout "main"
    commit id: "6574715" tag: "Merge pull request #6"
    commit id: "325eb70" tag: "Programa terminado"
    commit id: "3fc50e0" tag: "Refactor: Cambiar formato tiempo atencion"
    checkout "bug-fix-Problema-interfaz"
    commit id: "32ffbbc" tag: "Refactor: Tiempo atencion"
    checkout "main"
    merge "bug-fix-Problema-interfaz"
    commit id: "cb99c67" tag: "main"
    branch "feat-BestFit-Algorithm"
    checkout "feat-BestFit-Algorithm"
    commit id: "c27d2ac" tag: "Refactor: Ajustar .gitignore"
    commit id: "e55e31e" tag: "HEAD -> feat-BestFit-Algorithm, Refactor: Logica memoria al modulo, algoritmo BestFit"
    commit id: "" tag: "Refactor: Actualizar grafo"